# Develop override settings

#url: http://localhost:4000
url: https://mattk7.github.io # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"

analytics:
  provider: false

#comments:
#  disqus:
#    shortname            : "mmistakes-dev"

sass:
  style: expanded